// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 14 Nov 2023 12:28:21 +03.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nk

/*
#include "nk.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// IncludeDefaultAllocator as defined in nuklear/<predefined>:397
	IncludeDefaultAllocator = 1
	// IncludeFontBaking as defined in nuklear/<predefined>:398
	IncludeFontBaking = 1
	// IncludeDefaultFont as defined in nuklear/<predefined>:399
	IncludeDefaultFont = 1
	// IncludeVertexBufferOutput as defined in nuklear/<predefined>:400
	IncludeVertexBufferOutput = 1
	// IncludeFixedTypes as defined in nuklear/<predefined>:401
	IncludeFixedTypes = 1
	// IncludeStandardIo as defined in nuklear/<predefined>:402
	IncludeStandardIo = 1
	// SingleFile as defined in nk/nuklear.h:220

	// NuklearH as defined in nk/nuklear.h:224

	// Undefined as defined in nk/nuklear.h:236
	Undefined = (-1.0)
	// UtfSize as defined in nk/nuklear.h:238
	UtfSize = 4
	// InputMax as defined in nk/nuklear.h:240
	InputMax = 16
	// MaxNumberBuffer as defined in nk/nuklear.h:243
	MaxNumberBuffer = 64
	// ScrollbarHidingTimeout as defined in nk/nuklear.h:246
	ScrollbarHidingTimeout = 4.0
	// Lib as defined in nk/nuklear.h:270
	Lib = 0x5f8840
	// FileLine as defined in nk/nuklear.h:301
	FileLine = 0x5f8840
	// Bool as defined in nk/nuklear.h:407
	Bool = 0x5f8840
	// Strtod as defined in nk/nuklear.h:3781
	Strtod = 0x5f8840
	// TexteditUndostatecount as defined in nk/nuklear.h:4297
	TexteditUndostatecount = 99
	// TexteditUndocharcount as defined in nk/nuklear.h:4301
	TexteditUndocharcount = 999
	// MaxLayoutRowTemplateColumns as defined in nk/nuklear.h:5316
	MaxLayoutRowTemplateColumns = 16
	// ChartMaxSlot as defined in nk/nuklear.h:5319
	ChartMaxSlot = 4
	// WindowMaxName as defined in nk/nuklear.h:5418
	WindowMaxName = 64
	// ButtonBehaviorStackSize as defined in nk/nuklear.h:5532
	ButtonBehaviorStackSize = 8
	// FontStackSize as defined in nk/nuklear.h:5536
	FontStackSize = 8
	// StyleItemStackSize as defined in nk/nuklear.h:5540
	StyleItemStackSize = 16
	// FloatStackSize as defined in nk/nuklear.h:5544
	FloatStackSize = 32
	// VectorStackSize as defined in nk/nuklear.h:5548
	VectorStackSize = 16
	// FlagsStackSize as defined in nk/nuklear.h:5552
	FlagsStackSize = 32
	// ColorStackSize as defined in nk/nuklear.h:5556
	ColorStackSize = 32
	// Float as defined in nk/nuklear.h:5570
	Float = 0x5f8840
	// ValuePageCapacity as defined in nk/nuklear.h:5600
	ValuePageCapacity = 0x5f8840
	// Pi as defined in nk/nuklear.h:5684
	Pi = 3.141592654
	// UtfInvalid as defined in nk/nuklear.h:5685
	UtfInvalid = 0xFFFD
	// MaxFloatPrecision as defined in nk/nuklear.h:5686
	MaxFloatPrecision = 2
)

const (
	// False as declared in nk/nuklear.h:475
	False = iota
	// True as declared in nk/nuklear.h:475
	True = 1
)

const (
	// Up as declared in nk/nuklear.h:489
	Up = iota
	// Right as declared in nk/nuklear.h:489
	Right = 1
	// Down as declared in nk/nuklear.h:489
	Down = 2
	// Left as declared in nk/nuklear.h:489
	Left = 3
)

const (
	// ButtonDefault as declared in nk/nuklear.h:490
	ButtonDefault = iota
	// ButtonRepeater as declared in nk/nuklear.h:490
	ButtonRepeater = 1
)

const (
	// Fixed as declared in nk/nuklear.h:491
	Fixed = False
	// Modifiable as declared in nk/nuklear.h:491
	Modifiable = True
)

const (
	// Vertical as declared in nk/nuklear.h:492
	Vertical = iota
	// Horizontal as declared in nk/nuklear.h:492
	Horizontal = 1
)

const (
	// Minimized as declared in nk/nuklear.h:493
	Minimized = False
	// Maximized as declared in nk/nuklear.h:493
	Maximized = True
)

const (
	// Hidden as declared in nk/nuklear.h:494
	Hidden = False
	// Shown as declared in nk/nuklear.h:494
	Shown = True
)

const (
	// ChartLines as declared in nk/nuklear.h:495
	ChartLines = iota
	// ChartColumn as declared in nk/nuklear.h:495
	ChartColumn = 1
	// ChartMax as declared in nk/nuklear.h:495
	ChartMax = 2
)

const (
	// ChartHovering as declared in nk/nuklear.h:496
	ChartHovering = 0x01
	// ChartClicked as declared in nk/nuklear.h:496
	ChartClicked = 0x02
)

const (
	// ColorFormatRGB as declared in nk/nuklear.h:497
	ColorFormatRGB = iota
	// ColorFormatRGBA as declared in nk/nuklear.h:497
	ColorFormatRGBA = 1
)

const (
	// PopupStatic as declared in nk/nuklear.h:498
	PopupStatic = iota
	// PopupDynamic as declared in nk/nuklear.h:498
	PopupDynamic = 1
)

const (
	// Dynamic as declared in nk/nuklear.h:499
	Dynamic = iota
	// Static as declared in nk/nuklear.h:499
	Static = 1
)

const (
	// TreeNode as declared in nk/nuklear.h:500
	TreeNode = iota
	// TreeTab as declared in nk/nuklear.h:500
	TreeTab = 1
)

const (
	// SymbolNone as declared in nk/nuklear.h:514
	SymbolNone = iota
	// SymbolX as declared in nk/nuklear.h:515
	SymbolX = 1
	// SymbolUnderscore as declared in nk/nuklear.h:516
	SymbolUnderscore = 2
	// SymbolCircleSolid as declared in nk/nuklear.h:517
	SymbolCircleSolid = 3
	// SymbolCircleOutline as declared in nk/nuklear.h:518
	SymbolCircleOutline = 4
	// SymbolRectSolid as declared in nk/nuklear.h:519
	SymbolRectSolid = 5
	// SymbolRectOutline as declared in nk/nuklear.h:520
	SymbolRectOutline = 6
	// SymbolTriangleUp as declared in nk/nuklear.h:521
	SymbolTriangleUp = 7
	// SymbolTriangleDown as declared in nk/nuklear.h:522
	SymbolTriangleDown = 8
	// SymbolTriangleLeft as declared in nk/nuklear.h:523
	SymbolTriangleLeft = 9
	// SymbolTriangleRight as declared in nk/nuklear.h:524
	SymbolTriangleRight = 10
	// SymbolPlus as declared in nk/nuklear.h:525
	SymbolPlus = 11
	// SymbolMinus as declared in nk/nuklear.h:526
	SymbolMinus = 12
	// SymbolMax as declared in nk/nuklear.h:527
	SymbolMax = 13
)

const (
	// KeyNone as declared in nk/nuklear.h:756
	KeyNone = iota
	// KeyShift as declared in nk/nuklear.h:757
	KeyShift = 1
	// KeyCtrl as declared in nk/nuklear.h:758
	KeyCtrl = 2
	// KeyDel as declared in nk/nuklear.h:759
	KeyDel = 3
	// KeyEnter as declared in nk/nuklear.h:760
	KeyEnter = 4
	// KeyTab as declared in nk/nuklear.h:761
	KeyTab = 5
	// KeyBackspace as declared in nk/nuklear.h:762
	KeyBackspace = 6
	// KeyCopy as declared in nk/nuklear.h:763
	KeyCopy = 7
	// KeyCut as declared in nk/nuklear.h:764
	KeyCut = 8
	// KeyPaste as declared in nk/nuklear.h:765
	KeyPaste = 9
	// KeyUp as declared in nk/nuklear.h:766
	KeyUp = 10
	// KeyDown as declared in nk/nuklear.h:767
	KeyDown = 11
	// KeyLeft as declared in nk/nuklear.h:768
	KeyLeft = 12
	// KeyRight as declared in nk/nuklear.h:769
	KeyRight = 13
	// KeyTextInsertMode as declared in nk/nuklear.h:771
	KeyTextInsertMode = 14
	// KeyTextReplaceMode as declared in nk/nuklear.h:772
	KeyTextReplaceMode = 15
	// KeyTextResetMode as declared in nk/nuklear.h:773
	KeyTextResetMode = 16
	// KeyTextLineStart as declared in nk/nuklear.h:774
	KeyTextLineStart = 17
	// KeyTextLineEnd as declared in nk/nuklear.h:775
	KeyTextLineEnd = 18
	// KeyTextStart as declared in nk/nuklear.h:776
	KeyTextStart = 19
	// KeyTextEnd as declared in nk/nuklear.h:777
	KeyTextEnd = 20
	// KeyTextUndo as declared in nk/nuklear.h:778
	KeyTextUndo = 21
	// KeyTextRedo as declared in nk/nuklear.h:779
	KeyTextRedo = 22
	// KeyTextSelectAll as declared in nk/nuklear.h:780
	KeyTextSelectAll = 23
	// KeyTextWordLeft as declared in nk/nuklear.h:781
	KeyTextWordLeft = 24
	// KeyTextWordRight as declared in nk/nuklear.h:782
	KeyTextWordRight = 25
	// KeyScrollStart as declared in nk/nuklear.h:784
	KeyScrollStart = 26
	// KeyScrollEnd as declared in nk/nuklear.h:785
	KeyScrollEnd = 27
	// KeyScrollDown as declared in nk/nuklear.h:786
	KeyScrollDown = 28
	// KeyScrollUp as declared in nk/nuklear.h:787
	KeyScrollUp = 29
	// KeyMax as declared in nk/nuklear.h:788
	KeyMax = 30
)

const (
	// ButtonLeft as declared in nk/nuklear.h:791
	ButtonLeft = iota
	// ButtonMiddle as declared in nk/nuklear.h:792
	ButtonMiddle = 1
	// ButtonRight as declared in nk/nuklear.h:793
	ButtonRight = 2
	// ButtonDouble as declared in nk/nuklear.h:794
	ButtonDouble = 3
	// ButtonMax as declared in nk/nuklear.h:795
	ButtonMax = 4
)

const (
	// AntiAliasingOff as declared in nk/nuklear.h:1162
	AntiAliasingOff = iota
	// AntiAliasingOn as declared in nk/nuklear.h:1162
	AntiAliasingOn = 1
)

const (
	// ConvertSuccess as declared in nk/nuklear.h:1164
	ConvertSuccess = iota
	// ConvertInvalidParam as declared in nk/nuklear.h:1165
	ConvertInvalidParam = 1
	// ConvertCommandBufferFull as declared in nk/nuklear.h:1166
	ConvertCommandBufferFull = (1 << (1))
	// ConvertVertexBufferFull as declared in nk/nuklear.h:1167
	ConvertVertexBufferFull = (1 << (2))
	// ConvertElementBufferFull as declared in nk/nuklear.h:1168
	ConvertElementBufferFull = (1 << (3))
)

const (
	// WindowBorder as declared in nk/nuklear.h:1471
	WindowBorder = (1 << (0))
	// WindowMovable as declared in nk/nuklear.h:1472
	WindowMovable = (1 << (1))
	// WindowScalable as declared in nk/nuklear.h:1473
	WindowScalable = (1 << (2))
	// WindowClosable as declared in nk/nuklear.h:1474
	WindowClosable = (1 << (3))
	// WindowMinimizable as declared in nk/nuklear.h:1475
	WindowMinimizable = (1 << (4))
	// WindowNoScrollbar as declared in nk/nuklear.h:1476
	WindowNoScrollbar = (1 << (5))
	// WindowTitle as declared in nk/nuklear.h:1477
	WindowTitle = (1 << (6))
	// WindowScrollAutoHide as declared in nk/nuklear.h:1478
	WindowScrollAutoHide = (1 << (7))
	// WindowBackground as declared in nk/nuklear.h:1479
	WindowBackground = (1 << (8))
	// WindowScaleLeft as declared in nk/nuklear.h:1480
	WindowScaleLeft = (1 << (9))
	// WindowNoInput as declared in nk/nuklear.h:1481
	WindowNoInput = (1 << (10))
)

const (
	// WidgetInvalid as declared in nk/nuklear.h:3077
	WidgetInvalid = iota
	// WidgetValid as declared in nk/nuklear.h:3078
	WidgetValid = 1
	// WidgetRom as declared in nk/nuklear.h:3079
	WidgetRom = 2
)

const (
	// WidgetStateModified as declared in nk/nuklear.h:3082
	WidgetStateModified = (1 << (1))
	// WidgetStateInactive as declared in nk/nuklear.h:3083
	WidgetStateInactive = (1 << (2))
	// WidgetStateEntered as declared in nk/nuklear.h:3084
	WidgetStateEntered = (1 << (3))
	// WidgetStateHover as declared in nk/nuklear.h:3085
	WidgetStateHover = (1 << (4))
	// WidgetStateActived as declared in nk/nuklear.h:3086
	WidgetStateActived = (1 << (5))
	// WidgetStateLeft as declared in nk/nuklear.h:3087
	WidgetStateLeft = (1 << (6))
	// WidgetStateHovered as declared in nk/nuklear.h:3088
	WidgetStateHovered = WidgetStateHover | WidgetStateModified
	// WidgetStateActive as declared in nk/nuklear.h:3089
	WidgetStateActive = WidgetStateActived | WidgetStateModified
)

const (
	// TextAlignLeft as declared in nk/nuklear.h:3108
	TextAlignLeft = 0x01
	// TextAlignCentered as declared in nk/nuklear.h:3109
	TextAlignCentered = 0x02
	// TextAlignRight as declared in nk/nuklear.h:3110
	TextAlignRight = 0x04
	// TextAlignTop as declared in nk/nuklear.h:3111
	TextAlignTop = 0x08
	// TextAlignMiddle as declared in nk/nuklear.h:3112
	TextAlignMiddle = 0x10
	// TextAlignBottom as declared in nk/nuklear.h:3113
	TextAlignBottom = 0x20
)

const (
	// TextLeft as declared in nk/nuklear.h:3116
	TextLeft = TextAlignMiddle | TextAlignLeft
	// TextCentered as declared in nk/nuklear.h:3117
	TextCentered = TextAlignMiddle | TextAlignCentered
	// TextRight as declared in nk/nuklear.h:3118
	TextRight = TextAlignMiddle | TextAlignRight
)

const (
	// EditDefault as declared in nk/nuklear.h:3451
	EditDefault = iota
	// EditReadOnly as declared in nk/nuklear.h:3452
	EditReadOnly = (1 << (0))
	// EditAutoSelect as declared in nk/nuklear.h:3453
	EditAutoSelect = (1 << (1))
	// EditSigEnter as declared in nk/nuklear.h:3454
	EditSigEnter = (1 << (2))
	// EditAllowTab as declared in nk/nuklear.h:3455
	EditAllowTab = (1 << (3))
	// EditNoCursor as declared in nk/nuklear.h:3456
	EditNoCursor = (1 << (4))
	// EditSelectable as declared in nk/nuklear.h:3457
	EditSelectable = (1 << (5))
	// EditClipboard as declared in nk/nuklear.h:3458
	EditClipboard = (1 << (6))
	// EditCtrlEnterNewline as declared in nk/nuklear.h:3459
	EditCtrlEnterNewline = (1 << (7))
	// EditNoHorizontalScroll as declared in nk/nuklear.h:3460
	EditNoHorizontalScroll = (1 << (8))
	// EditAlwaysInsertMode as declared in nk/nuklear.h:3461
	EditAlwaysInsertMode = (1 << (9))
	// EditMultiline as declared in nk/nuklear.h:3462
	EditMultiline = (1 << (10))
	// EditGotoEndOnActivate as declared in nk/nuklear.h:3463
	EditGotoEndOnActivate = (1 << (11))
)

const (
	// EditSimple as declared in nk/nuklear.h:3466
	EditSimple = EditAlwaysInsertMode
	// EditField as declared in nk/nuklear.h:3467
	EditField = EditSimple | EditSelectable | EditClipboard
	// EditBox as declared in nk/nuklear.h:3468
	EditBox = EditAlwaysInsertMode | EditSelectable | EditMultiline | EditAllowTab | EditClipboard
	// EditEditor as declared in nk/nuklear.h:3469
	EditEditor = EditSelectable | EditMultiline | EditAllowTab | EditClipboard
)

const (
	// EditActive as declared in nk/nuklear.h:3472
	EditActive = (1 << (0))
	// EditInactive as declared in nk/nuklear.h:3473
	EditInactive = (1 << (1))
	// EditActivated as declared in nk/nuklear.h:3474
	EditActivated = (1 << (2))
	// EditDeactivated as declared in nk/nuklear.h:3475
	EditDeactivated = (1 << (3))
	// EditCommited as declared in nk/nuklear.h:3476
	EditCommited = (1 << (4))
)

const (
	// ColorText as declared in nk/nuklear.h:3597
	ColorText = iota
	// ColorWindow as declared in nk/nuklear.h:3598
	ColorWindow = 1
	// ColorHeader as declared in nk/nuklear.h:3599
	ColorHeader = 2
	// ColorBorder as declared in nk/nuklear.h:3600
	ColorBorder = 3
	// ColorButton as declared in nk/nuklear.h:3601
	ColorButton = 4
	// ColorButtonHover as declared in nk/nuklear.h:3602
	ColorButtonHover = 5
	// ColorButtonActive as declared in nk/nuklear.h:3603
	ColorButtonActive = 6
	// ColorToggle as declared in nk/nuklear.h:3604
	ColorToggle = 7
	// ColorToggleHover as declared in nk/nuklear.h:3605
	ColorToggleHover = 8
	// ColorToggleCursor as declared in nk/nuklear.h:3606
	ColorToggleCursor = 9
	// ColorSelect as declared in nk/nuklear.h:3607
	ColorSelect = 10
	// ColorSelectActive as declared in nk/nuklear.h:3608
	ColorSelectActive = 11
	// ColorSlider as declared in nk/nuklear.h:3609
	ColorSlider = 12
	// ColorSliderCursor as declared in nk/nuklear.h:3610
	ColorSliderCursor = 13
	// ColorSliderCursorHover as declared in nk/nuklear.h:3611
	ColorSliderCursorHover = 14
	// ColorSliderCursorActive as declared in nk/nuklear.h:3612
	ColorSliderCursorActive = 15
	// ColorProperty as declared in nk/nuklear.h:3613
	ColorProperty = 16
	// ColorEdit as declared in nk/nuklear.h:3614
	ColorEdit = 17
	// ColorEditCursor as declared in nk/nuklear.h:3615
	ColorEditCursor = 18
	// ColorCombo as declared in nk/nuklear.h:3616
	ColorCombo = 19
	// ColorChart as declared in nk/nuklear.h:3617
	ColorChart = 20
	// ColorChartColor as declared in nk/nuklear.h:3618
	ColorChartColor = 21
	// ColorChartColorHighlight as declared in nk/nuklear.h:3619
	ColorChartColorHighlight = 22
	// ColorScrollbar as declared in nk/nuklear.h:3620
	ColorScrollbar = 23
	// ColorScrollbarCursor as declared in nk/nuklear.h:3621
	ColorScrollbarCursor = 24
	// ColorScrollbarCursorHover as declared in nk/nuklear.h:3622
	ColorScrollbarCursorHover = 25
	// ColorScrollbarCursorActive as declared in nk/nuklear.h:3623
	ColorScrollbarCursorActive = 26
	// ColorTabHeader as declared in nk/nuklear.h:3624
	ColorTabHeader = 27
	// ColorCount as declared in nk/nuklear.h:3625
	ColorCount = 28
)

const (
	// CursorArrow as declared in nk/nuklear.h:3628
	CursorArrow = iota
	// CursorText as declared in nk/nuklear.h:3629
	CursorText = 1
	// CursorMove as declared in nk/nuklear.h:3630
	CursorMove = 2
	// CursorResizeVertical as declared in nk/nuklear.h:3631
	CursorResizeVertical = 3
	// CursorResizeHorizontal as declared in nk/nuklear.h:3632
	CursorResizeHorizontal = 4
	// CursorResizeTopLeftDownRight as declared in nk/nuklear.h:3633
	CursorResizeTopLeftDownRight = 5
	// CursorResizeTopRightDownLeft as declared in nk/nuklear.h:3634
	CursorResizeTopRightDownLeft = 6
	// CursorCount as declared in nk/nuklear.h:3635
	CursorCount = 7
)

const (
	// CoordUv as declared in nk/nuklear.h:3987
	CoordUv = iota
	// CoordPixel as declared in nk/nuklear.h:3988
	CoordPixel = 1
)

const (
	// FontAtlasAlpha8 as declared in nk/nuklear.h:4061
	FontAtlasAlpha8 = iota
	// FontAtlasRgba32 as declared in nk/nuklear.h:4062
	FontAtlasRgba32 = 1
)

const (
	// BufferFixed as declared in nk/nuklear.h:4159
	BufferFixed = iota
	// BufferDynamic as declared in nk/nuklear.h:4160
	BufferDynamic = 1
)

const (
	// BufferFront as declared in nk/nuklear.h:4164
	BufferFront = iota
	// BufferBack as declared in nk/nuklear.h:4165
	BufferBack = 1
	// BufferMax as declared in nk/nuklear.h:4166
	BufferMax = 2
)

const (
	// TextEditSingleLine as declared in nk/nuklear.h:4328
	TextEditSingleLine = iota
	// TextEditMultiLine as declared in nk/nuklear.h:4329
	TextEditMultiLine = 1
)

const (
	// TextEditModeView as declared in nk/nuklear.h:4333
	TextEditModeView = iota
	// TextEditModeInsert as declared in nk/nuklear.h:4334
	TextEditModeInsert = 1
	// TextEditModeReplace as declared in nk/nuklear.h:4335
	TextEditModeReplace = 2
)

const (
	// CommandTypeNop as declared in nk/nuklear.h:4436
	CommandTypeNop = iota
	// CommandTypeScissor as declared in nk/nuklear.h:4437
	CommandTypeScissor = 1
	// CommandTypeLine as declared in nk/nuklear.h:4438
	CommandTypeLine = 2
	// CommandTypeCurve as declared in nk/nuklear.h:4439
	CommandTypeCurve = 3
	// CommandTypeRect as declared in nk/nuklear.h:4440
	CommandTypeRect = 4
	// CommandTypeRectFilled as declared in nk/nuklear.h:4441
	CommandTypeRectFilled = 5
	// CommandTypeRectMultiColor as declared in nk/nuklear.h:4442
	CommandTypeRectMultiColor = 6
	// CommandTypeCircle as declared in nk/nuklear.h:4443
	CommandTypeCircle = 7
	// CommandTypeCircleFilled as declared in nk/nuklear.h:4444
	CommandTypeCircleFilled = 8
	// CommandTypeArc as declared in nk/nuklear.h:4445
	CommandTypeArc = 9
	// CommandTypeArcFilled as declared in nk/nuklear.h:4446
	CommandTypeArcFilled = 10
	// CommandTypeTriangle as declared in nk/nuklear.h:4447
	CommandTypeTriangle = 11
	// CommandTypeTriangleFilled as declared in nk/nuklear.h:4448
	CommandTypeTriangleFilled = 12
	// CommandTypePolygon as declared in nk/nuklear.h:4449
	CommandTypePolygon = 13
	// CommandTypePolygonFilled as declared in nk/nuklear.h:4450
	CommandTypePolygonFilled = 14
	// CommandTypePolyline as declared in nk/nuklear.h:4451
	CommandTypePolyline = 15
	// CommandTypeText as declared in nk/nuklear.h:4452
	CommandTypeText = 16
	// CommandTypeImage as declared in nk/nuklear.h:4453
	CommandTypeImage = 17
	// CommandTypeCustom as declared in nk/nuklear.h:4454
	CommandTypeCustom = 18
)

const (
	// ClippingOff as declared in nk/nuklear.h:4619
	ClippingOff = False
	// ClippingOn as declared in nk/nuklear.h:4620
	ClippingOn = True
)

const (
	// StrokeOpen as declared in nk/nuklear.h:4738
	StrokeOpen = False
	// StrokeClosed as declared in nk/nuklear.h:4740
	StrokeClosed = True
)

const (
	// VertexPosition as declared in nk/nuklear.h:4745
	VertexPosition = iota
	// VertexColor as declared in nk/nuklear.h:4746
	VertexColor = 1
	// VertexTexcoord as declared in nk/nuklear.h:4747
	VertexTexcoord = 2
	// VertexAttributeCount as declared in nk/nuklear.h:4748
	VertexAttributeCount = 3
)

const (
	// FormatSchar as declared in nk/nuklear.h:4752
	FormatSchar = iota
	// FormatSshort as declared in nk/nuklear.h:4753
	FormatSshort = 1
	// FormatSint as declared in nk/nuklear.h:4754
	FormatSint = 2
	// FormatUchar as declared in nk/nuklear.h:4755
	FormatUchar = 3
	// FormatUshort as declared in nk/nuklear.h:4756
	FormatUshort = 4
	// FormatUint as declared in nk/nuklear.h:4757
	FormatUint = 5
	// FormatFloat as declared in nk/nuklear.h:4758
	FormatFloat = 6
	// FormatDouble as declared in nk/nuklear.h:4759
	FormatDouble = 7
	// FormatColorBegin as declared in nk/nuklear.h:4761
	FormatColorBegin = 8
	// FormatR8g8b8 as declared in nk/nuklear.h:4762
	FormatR8g8b8 = FormatColorBegin
	// FormatR16g15b16 as declared in nk/nuklear.h:4763
	FormatR16g15b16 = 9
	// FormatR32g32b32 as declared in nk/nuklear.h:4764
	FormatR32g32b32 = 10
	// FormatR8g8b8a8 as declared in nk/nuklear.h:4766
	FormatR8g8b8a8 = 11
	// FormatB8g8r8a8 as declared in nk/nuklear.h:4767
	FormatB8g8r8a8 = 12
	// FormatR16g15b16a16 as declared in nk/nuklear.h:4768
	FormatR16g15b16a16 = 13
	// FormatR32g32b32a32 as declared in nk/nuklear.h:4769
	FormatR32g32b32a32 = 14
	// FormatR32g32b32a32Float as declared in nk/nuklear.h:4770
	FormatR32g32b32a32Float = 15
	// FormatR32g32b32a32Double as declared in nk/nuklear.h:4771
	FormatR32g32b32a32Double = 16
	// FormatRgb32 as declared in nk/nuklear.h:4773
	FormatRgb32 = 17
	// FormatRgba32 as declared in nk/nuklear.h:4774
	FormatRgba32 = 18
	// FormatColorEnd as declared in nk/nuklear.h:4775
	FormatColorEnd = FormatRgba32
	// FormatCount as declared in nk/nuklear.h:4776
	FormatCount = 19
)

const (
	// StyleItemColor as declared in nk/nuklear.h:4873
	StyleItemColor = iota
	// StyleItemImage as declared in nk/nuklear.h:4874
	StyleItemImage = 1
	// StyleItemNineSlice as declared in nk/nuklear.h:4875
	StyleItemNineSlice = 2
)

const (
	// HeaderLeft as declared in nk/nuklear.h:5216
	HeaderLeft = iota
	// HeaderRight as declared in nk/nuklear.h:5217
	HeaderRight = 1
)

const (
	// PanelNone as declared in nk/nuklear.h:5323
	PanelNone = iota
	// PanelWindow as declared in nk/nuklear.h:5324
	PanelWindow = (1 << (0))
	// PanelGroup as declared in nk/nuklear.h:5325
	PanelGroup = (1 << (1))
	// PanelPopup as declared in nk/nuklear.h:5326
	PanelPopup = (1 << (2))
	// PanelContextual as declared in nk/nuklear.h:5327
	PanelContextual = (1 << (4))
	// PanelCombo as declared in nk/nuklear.h:5328
	PanelCombo = (1 << (5))
	// PanelMenu as declared in nk/nuklear.h:5329
	PanelMenu = (1 << (6))
	// PanelTooltip as declared in nk/nuklear.h:5330
	PanelTooltip = (1 << (7))
)

const (
	// PanelSetNonblock as declared in nk/nuklear.h:5333
	PanelSetNonblock = PanelContextual | PanelCombo | PanelMenu | PanelTooltip
	// PanelSetPopup as declared in nk/nuklear.h:5334
	PanelSetPopup = PanelSetNonblock | PanelPopup
	// PanelSetSub as declared in nk/nuklear.h:5335
	PanelSetSub = PanelSetPopup | PanelGroup
)

const (
	// LayoutDynamicFixed as declared in nk/nuklear.h:5355
	LayoutDynamicFixed = iota
	// LayoutDynamicRow as declared in nk/nuklear.h:5356
	LayoutDynamicRow = 1
	// LayoutDynamicFree as declared in nk/nuklear.h:5357
	LayoutDynamicFree = 2
	// LayoutDynamic as declared in nk/nuklear.h:5358
	LayoutDynamic = 3
	// LayoutStaticFixed as declared in nk/nuklear.h:5359
	LayoutStaticFixed = 4
	// LayoutStaticRow as declared in nk/nuklear.h:5360
	LayoutStaticRow = 5
	// LayoutStaticFree as declared in nk/nuklear.h:5361
	LayoutStaticFree = 6
	// LayoutStatic as declared in nk/nuklear.h:5362
	LayoutStatic = 7
	// LayoutTemplate as declared in nk/nuklear.h:5363
	LayoutTemplate = 8
	// LayoutCount as declared in nk/nuklear.h:5364
	LayoutCount = 9
)

const (
	// WindowPrivate as declared in nk/nuklear.h:5423
	WindowPrivate = (1 << (11))
	// WindowDynamic as declared in nk/nuklear.h:5424
	WindowDynamic = WindowPrivate
	// WindowRom as declared in nk/nuklear.h:5426
	WindowRom = (1 << (12))
	// WindowNotInteractive as declared in nk/nuklear.h:5428
	WindowNotInteractive = WindowRom | WindowNoInput
	// WindowHidden as declared in nk/nuklear.h:5430
	WindowHidden = (1 << (13))
	// WindowClosed as declared in nk/nuklear.h:5432
	WindowClosed = (1 << (14))
	// WindowMinimized as declared in nk/nuklear.h:5434
	WindowMinimized = (1 << (15))
	// WindowRemoveRom as declared in nk/nuklear.h:5436
	WindowRemoveRom = (1 << (16))
)
