// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 22 Sep 2016 02:14:02 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package nk provides Go bindings for nuklear.h
*/
package nk
