// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 12 Dec 2017 20:09:32 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package nk provides Go bindings for nuklear.h — a small ANSI C gui library.
*/
package nk
