// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Sep 2016 23:01:35 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package nk

/*
#cgo CFLAGS: -DNK_INCLUDE_FIXED_TYPES -DNK_INCLUDE_STANDARD_IO -DNK_INCLUDE_DEFAULT_ALLOCATOR -DNK_INCLUDE_FONT_BAKING -DNK_INCLUDE_DEFAULT_FONT -Wno-implicit-function-declaration
#include "nuklear.h"
#include "nuklear_glfw_gl3.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Char type as declared in nk/nuklear.h:370
type Char byte

// Uchar type as declared in nk/nuklear.h:371
type Uchar byte

// Byte type as declared in nk/nuklear.h:372
type Byte byte

// Short type as declared in nk/nuklear.h:373
type Short int16

// Ushort type as declared in nk/nuklear.h:374
type Ushort uint16

// Int type as declared in nk/nuklear.h:375
type Int int32

// Uint type as declared in nk/nuklear.h:376
type Uint uint32

// Size type as declared in nk/nuklear.h:377
type Size uint

// Ptr type as declared in nk/nuklear.h:378
type Ptr uint

// Hash type as declared in nk/nuklear.h:380
type Hash uint32

// Flags type as declared in nk/nuklear.h:381
type Flags uint32

// Rune type as declared in nk/nuklear.h:382
type Rune uint32

// Glyph type as declared in nk/nuklear.h:422
type Glyph [4]byte

// Handle as declared in nk/nuklear.h:423
const sizeofHandle = unsafe.Sizeof(C.nk_handle{})

type Handle [sizeofHandle]byte

// PluginAlloc type as declared in nk/nuklear.h:442
type PluginAlloc func(arg0 Handle, old unsafe.Pointer, arg2 Size) unsafe.Pointer

// PluginFree type as declared in nk/nuklear.h:443
type PluginFree func(arg0 Handle, old unsafe.Pointer)

// PluginFilter type as declared in nk/nuklear.h:444
type PluginFilter func(arg0 *TextEdit, unicode Rune) int32

// PluginPaste type as declared in nk/nuklear.h:445
type PluginPaste func(arg0 Handle, arg1 *TextEdit)

// PluginCopy type as declared in nk/nuklear.h:446
type PluginCopy func(arg0 Handle, arg1 string, len int32)

// TextWidthF type as declared in nk/nuklear.h:1380
type TextWidthF func(arg0 Handle, h float32, arg2 string, len int32) float32

// QueryFontGlyphF type as declared in nk/nuklear.h:1381
type QueryFontGlyphF func(handle Handle, fontHeight float32, glyph *UserFontGlyph, codepoint Rune, nextCodepoint Rune)

// PropertyState as declared in nk/nuklear.h:2541
type PropertyState C.struct_nk_property_state

// CommandRect as declared in nk/nuklear.h:1612
type CommandRect C.struct_nk_command_rect

// ConfigStackUserFontElement as declared in nk/nuklear.h:2627
type ConfigStackUserFontElement struct {
	Address        [][]UserFont
	OldValue       []UserFont
	ref5572630c    *C.struct_nk_config_stack_user_font_element
	allocs5572630c interface{}
}

// PageData as declared in nk/nuklear.h:2660
const sizeofPageData = unsafe.Sizeof(C.union_nk_page_data{})

type PageData [sizeofPageData]byte

// Command as declared in nk/nuklear.h:1581
type Command C.struct_nk_command

// PopupState as declared in nk/nuklear.h:2517
type PopupState C.struct_nk_popup_state

// Mouse as declared in nk/nuklear.h:1780
type Mouse C.struct_nk_mouse

// Recti as declared in nk/nuklear.h:421
type Recti C.struct_nk_recti

// ConfigStackFloatElement as declared in nk/nuklear.h:2623
type ConfigStackFloatElement C.struct_nk_config_stack_float_element

// UserFont as declared in nk/nuklear.h:410
type UserFont struct {
	Userdata       Handle
	Height         float32
	Width          TextWidthF
	ref738ce62e    *C.struct_nk_user_font
	allocs738ce62e interface{}
}

// CommandArc as declared in nk/nuklear.h:1671
type CommandArc C.struct_nk_command_arc

// StyleTab as declared in nk/nuklear.h:2292
type StyleTab C.struct_nk_style_tab

// Key as declared in nk/nuklear.h:1791
type Key C.struct_nk_key

// ConfigStackFlags as declared in nk/nuklear.h:2633
type ConfigStackFlags C.struct_nk_config_stack_flags

// FontConfig as declared in nk/nuklear.h:1432
type FontConfig C.struct_nk_font_config

// CommandTriangle as declared in nk/nuklear.h:1639
type CommandTriangle C.struct_nk_command_triangle

// CommandLine as declared in nk/nuklear.h:1595
type CommandLine C.struct_nk_command_line

// ConfigStackFloat as declared in nk/nuklear.h:2631
type ConfigStackFloat C.struct_nk_config_stack_float

// DrawList as declared in nk/nuklear.h:409
type DrawList C.struct_nk_draw_list

// Font as declared in nk/nuklear.h:1473
type Font C.struct_nk_font

// CommandRectFilled as declared in nk/nuklear.h:1621
type CommandRectFilled C.struct_nk_command_rect_filled

// Cursor as declared in nk/nuklear.h:425
type Cursor C.struct_nk_cursor

// ConfigStackVec2 as declared in nk/nuklear.h:2632
type ConfigStackVec2 C.struct_nk_config_stack_vec2

// StyleWindowHeader as declared in nk/nuklear.h:2319
type StyleWindowHeader C.struct_nk_style_window_header

// ConfigStackStyleItemElement as declared in nk/nuklear.h:2622
type ConfigStackStyleItemElement C.struct_nk_config_stack_style_item_element

// Pool as declared in nk/nuklear.h:2677
type Pool C.struct_nk_pool

// StyleCombo as declared in nk/nuklear.h:2261
type StyleCombo C.struct_nk_style_combo

// CommandScissor as declared in nk/nuklear.h:1589
type CommandScissor C.struct_nk_command_scissor

// UserFontGlyph as declared in nk/nuklear.h:1379
type UserFontGlyph C.struct_nk_user_font_glyph

// CommandPolyline as declared in nk/nuklear.h:1703
type CommandPolyline C.struct_nk_command_polyline

// Chart as declared in nk/nuklear.h:2442
type Chart C.struct_nk_chart

// CommandImage as declared in nk/nuklear.h:1711
type CommandImage C.struct_nk_command_image

// TextUndoRecord as declared in nk/nuklear.h:1265
type TextUndoRecord C.struct_nk_text_undo_record

// ConfigStackColor as declared in nk/nuklear.h:2634
type ConfigStackColor C.struct_nk_config_stack_color

// TextUndoState as declared in nk/nuklear.h:1272
type TextUndoState C.struct_nk_text_undo_state

// TextEdit as declared in nk/nuklear.h:408
type TextEdit C.struct_nk_text_edit

// Memory as declared in nk/nuklear.h:1131
type Memory C.struct_nk_memory

// StyleToggle as declared in nk/nuklear.h:2020
type StyleToggle C.struct_nk_style_toggle

// MemoryStatus as declared in nk/nuklear.h:1106
type MemoryStatus C.struct_nk_memory_status

// StyleSlider as declared in nk/nuklear.h:2085
type StyleSlider C.struct_nk_style_slider

// ConfigStackVec2Element as declared in nk/nuklear.h:2624
type ConfigStackVec2Element C.struct_nk_config_stack_vec2_element

// StyleText as declared in nk/nuklear.h:1988
type StyleText C.struct_nk_style_text

// ConfigStackFlagsElement as declared in nk/nuklear.h:2625
type ConfigStackFlagsElement C.struct_nk_config_stack_flags_element

// ConfigStackStyleItem as declared in nk/nuklear.h:2630
type ConfigStackStyleItem C.struct_nk_config_stack_style_item

// StyleWindow as declared in nk/nuklear.h:2344
type StyleWindow C.struct_nk_style_window

// CommandTriangleFilled as declared in nk/nuklear.h:1648
type CommandTriangleFilled C.struct_nk_command_triangle_filled

// Image as declared in nk/nuklear.h:424
type Image C.struct_nk_image

// StyleEdit as declared in nk/nuklear.h:2183
type StyleEdit C.struct_nk_style_edit

// ConvertConfig as declared in nk/nuklear.h:406
type ConvertConfig C.struct_nk_convert_config

// ConfigStackButtonBehaviorElement as declared in nk/nuklear.h:2628
type ConfigStackButtonBehaviorElement C.struct_nk_config_stack_button_behavior_element

// MouseButton as declared in nk/nuklear.h:1774
type MouseButton C.struct_nk_mouse_button

// StyleItem as declared in nk/nuklear.h:407
type StyleItem C.struct_nk_style_item

// Context as declared in nk/nuklear.h:412
type Context C.struct_nk_context

// MenuState as declared in nk/nuklear.h:2469
type MenuState C.struct_nk_menu_state

// StyleProperty as declared in nk/nuklear.h:2217
type StyleProperty C.struct_nk_style_property

// BakedFont as declared in nk/nuklear.h:1419
type BakedFont C.struct_nk_baked_font

// DrawVertexLayoutElement as declared in nk/nuklear.h:413
type DrawVertexLayoutElement C.struct_nk_draw_vertex_layout_element

// StyleButton as declared in nk/nuklear.h:1993
type StyleButton C.struct_nk_style_button

// Table as declared in nk/nuklear.h:2500
type Table C.struct_nk_table

// CommandRectMultiColor as declared in nk/nuklear.h:1629
type CommandRectMultiColor C.struct_nk_command_rect_multi_color

// Style as declared in nk/nuklear.h:2380
type Style C.struct_nk_style

// FontGlyph as declared in nk/nuklear.h:1466
type FontGlyph C.struct_nk_font_glyph

// EditState as declared in nk/nuklear.h:2528
type EditState C.struct_nk_edit_state

// ChartSlot as declared in nk/nuklear.h:2432
type ChartSlot C.struct_nk_chart_slot

// CommandText as declared in nk/nuklear.h:1719
type CommandText C.struct_nk_command_text

// RowLayout as declared in nk/nuklear.h:2448
type RowLayout C.struct_nk_row_layout

// Vec2 as declared in nk/nuklear.h:418
type Vec2 C.struct_nk_vec2

// CommandCircle as declared in nk/nuklear.h:1656
type CommandCircle C.struct_nk_command_circle

// Str as declared in nk/nuklear.h:1176
type Str C.struct_nk_str

// Keyboard as declared in nk/nuklear.h:1796
type Keyboard C.struct_nk_keyboard

// Page as declared in nk/nuklear.h:2671
type Page C.struct_nk_page

// Window as declared in nk/nuklear.h:2552
type Window C.struct_nk_window

// CommandCurve as declared in nk/nuklear.h:1603
type CommandCurve C.struct_nk_command_curve

// Panel as declared in nk/nuklear.h:411
type Panel C.struct_nk_panel

// Clipboard as declared in nk/nuklear.h:1259
type Clipboard C.struct_nk_clipboard

// DrawNullTexture as declared in nk/nuklear.h:454
type DrawNullTexture C.struct_nk_draw_null_texture

// Scroll as declared in nk/nuklear.h:426
type Scroll C.struct_nk_scroll

// FontAtlas as declared in nk/nuklear.h:1490
type FontAtlas C.struct_nk_font_atlas

// Input as declared in nk/nuklear.h:1802
type Input C.struct_nk_input

// ConfigStackUserFont as declared in nk/nuklear.h:2635
type ConfigStackUserFont struct {
	Head           int32
	Elements       [8]ConfigStackUserFontElement
	refa664861d    *C.struct_nk_config_stack_user_font
	allocsa664861d interface{}
}

// StyleProgress as declared in nk/nuklear.h:2124
type StyleProgress C.struct_nk_style_progress

// StyleSelectable as declared in nk/nuklear.h:2050
type StyleSelectable C.struct_nk_style_selectable

// Vec2i as declared in nk/nuklear.h:419
type Vec2i C.struct_nk_vec2i

// CommandCircleFilled as declared in nk/nuklear.h:1664
type CommandCircleFilled C.struct_nk_command_circle_filled

// Colorf as declared in nk/nuklear.h:417
type Colorf C.struct_nk_colorf

// Rect as declared in nk/nuklear.h:420
type Rect C.struct_nk_rect

// ConfigStackColorElement as declared in nk/nuklear.h:2626
type ConfigStackColorElement C.struct_nk_config_stack_color_element

// StyleScrollbar as declared in nk/nuklear.h:2150
type StyleScrollbar C.struct_nk_style_scrollbar

// Allocator as declared in nk/nuklear.h:403
type Allocator C.struct_nk_allocator

// StyleChart as declared in nk/nuklear.h:2248
type StyleChart C.struct_nk_style_chart

// Buffer as declared in nk/nuklear.h:402
type Buffer C.struct_nk_buffer

// PageElement as declared in nk/nuklear.h:2665
type PageElement C.struct_nk_page_element

// ConfigurationStacks as declared in nk/nuklear.h:2638
type ConfigurationStacks C.struct_nk_configuration_stacks

// CommandPolygonFilled as declared in nk/nuklear.h:1696
type CommandPolygonFilled C.struct_nk_command_polygon_filled

// PopupBuffer as declared in nk/nuklear.h:2461
type PopupBuffer C.struct_nk_popup_buffer

// CommandArcFilled as declared in nk/nuklear.h:1680
type CommandArcFilled C.struct_nk_command_arc_filled

// BufferMarker as declared in nk/nuklear.h:1126
type BufferMarker C.struct_nk_buffer_marker

// DrawCommand as declared in nk/nuklear.h:405
type DrawCommand C.struct_nk_draw_command

// Color as declared in nk/nuklear.h:416
type Color C.struct_nk_color

// CommandBuffer as declared in nk/nuklear.h:404
type CommandBuffer C.struct_nk_command_buffer

// StyleItemData as declared in nk/nuklear.h:1978
const sizeofStyleItemData = unsafe.Sizeof(C.union_nk_style_item_data{})

type StyleItemData [sizeofStyleItemData]byte

// ConfigStackButtonBehavior as declared in nk/nuklear.h:2636
type ConfigStackButtonBehavior C.struct_nk_config_stack_button_behavior

// CommandPolygon as declared in nk/nuklear.h:1688
type CommandPolygon C.struct_nk_command_polygon
